### ISSUE TITLE
can work with private gitlab packages?

### ISSUE THREAD

**Issue by jomonkj** [yiisoft/yii-dev-tool#1]

**Comment by cebe** [comment]
what do you mean? Please explain more about what you are asking.

**Comment by jomonkj** [comment]
from [here](https://github.com/yiisoft/yii-dev/blob/master/commands/InstallCommand.php#L65),
 I think your not considering gitlab, bitbuckets or other Git-repository manager.

**Comment by jomonkj** [comment]
then, how developer manage/work in their private Yii packages?

**Comment by samdark** [comment]
OK, that may make sense...

**Comment by cebe** [comment]
The scope of this project is currently limited to managing Yii core repositories, if it works out well, we can enhance it to allow working with other packages and repos as well.

**Comment by FabrizioCaldarelli** [comment]
yii-dev name is a bit confusing. Maybe yii-tool or yii-install or something related to installation phase is better.

**Comment by FabrizioCaldarelli** [comment]
> then, how developer manage/work in their private Yii packages?

In composer.json point the package to private git repository

**Comment by samdark** [comment]
@FabrizioCaldarelli it is not `install` or `setup`. It is meant to aid development of the Yii itself.

**Comment by FabrizioCaldarelli** [comment]
@samdark Can't it be used to install yii dependencies for a normal app? It should work well.

**Comment by samdark** [comment]
You mean if you want to both work on your app and contribute to Yii? That would likely work. I haven't tried it so can't be sure.

**Comment by lubosdz** [comment]
Confusing non-unique package name. Better would be e.g.
* yii-tool
* yii-maker
* yii-builder
* ...

**Comment by samdark** [comment]
Yes, `yii-dev-tool` or alike name may describe it better.

**Comment by rugabarbo** [comment]
Guys, are we really going to rename this repository? If so, then it is better not to delay it. Link to the repository is already distributed in many places...

**Comment by samdark** [comment]
Renamed.

**Comment by rugabarbo** [comment]
After merge request #24, rename [the repository in Travis](https://travis-ci.com/yiisoft/yii-dev), and then I can make changes to package [yiisoft/docs](https://github.com/yiisoft/docs). There are references to Travis links: https://github.com/yiisoft/docs/blob/master/000-packages.md

**Comment by samdark** [comment]
Travis needs some time before changes are visible. Not there yet...

**Comment by rugabarbo** [comment]
See the last paragraph [here](https://docs.travis-ci.com/user/encryption-keys#fetching-the-public-key-for-your-repository):

> Note, travis uses `travis.slug` in your project to determine the endpoints if it exists (check by using `git config --local travis.slug`), **if you rename your repo or move your repo to another user/organization, you might need to change it.**

**Comment by samdark** [comment]
We don't have `travis.slug`.

**Comment by rugabarbo** [comment]
Hmm ... So, in our case, we just need to wait until Travis sees the changes?

**Comment by samdark** [comment]
I think so.

**Comment by rugabarbo** [comment]
@samdark also adjust your post on the forum, please: https://forum.yiiframework.com/t/contributing-to-yii-3/127369

**Comment by samdark** [comment]
Forum post done.

**Comment by samdark** [comment]
Travis done.
