### ISSUE TITLE
What's about MVC collectors/reflection/name validators?

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii-dev-tool#163]
Sorry if this is an inappropriate question for current package, but where contained MVC reflection/helpers? What classes/methods have that's functionality?

How get list of

- module/application controllers/commands
- controller actions
- route controllers and actions (controllers/actions matches route)

How check/validate

- class is controller/command
- method/class is action

How convert

- class name to controller/command id
- method/class name to action id

**Comment by samdark** [comment]
1. Is the question about Yii 3?
2. What are "MVC reflection/helpers"?
3. To get a list of routes and their handlers, check the routes config: https://github.com/yiisoft/yii-demo/blob/master/config/routes.php. You don't need to validate if route handler is a controller (or I don't get the question).
4. There's no such thing as controller/command id. There's a name you can set explicitly in routes config and then use it for generating URLs.

**Comment by samdark** [comment]
btw., there's a chat in Telegram. It's a bit more suitable for questions: https://t.me/yii3ru

**Comment by WinterSilence** [comment]
1. yes, yii2 don't contained that's
2. What are "MVC reflection/helpers"? classes contains methods for get answers
3. I read `yiisoft/docs` , but don't find information about application controllers in yii3. I'm looked `yiisoft/yii-web` and demo application but can't understand: if controllers is middleware, then why application controllers don't exntends `MiddlewareInterface`? Controllers don't have parents as commands extends `Command`  - it's confuse me

thanks for help
