### ISSUE TITLE
Packages to develop are duplicated

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii-dev-tool#195]
See https://t.me/yii3ru/71528.

**Comment by DAGpro** [comment]
actual issue?

**Comment by vjik** [comment]
> actual issue?

Seems, yes. Need test. See packages in `yiisoft/active-record`:

![image](https://user-images.githubusercontent.com/525501/190863751-04a3fb40-481e-434a-af61-57154462dc44.png)

**Comment by DAGpro** [comment]
"release when" command should be corrected?
It's not clear from the first comment

**Comment by vjik** [comment]
In line `yiisoft/active-record` package `db-oracle` is duplicated:

![image](https://user-images.githubusercontent.com/525501/190867487-c780fdcc-3d93-4d66-a738-da13e30b94a1.png)

**Comment by DAGpro** [comment]
Duplication could occur on these lines https://github.com/yiisoft/yii-dev-tool/blob/fb60fcfef8ed88362957c3519dd4987c9be65e78/src/App/Command/Release/WhatCommand.php#L223-L236

When adding to the require section in compose.json, the error was reproduced

In the change history of the active-record package, I did not find duplicate dependencies.

dev dependencies must be removed or merged all dependencies?

**Comment by vjik** [comment]
`array_unique` should resolve problem.

**Comment by DAGpro** [comment]
A possible reason for duplication in the combination of in out packages was also noticed.

https://github.com/yiisoft/yii-dev-tool/blob/fb60fcfef8ed88362957c3519dd4987c9be65e78/src/App/Command/Release/WhatCommand.php#L127-L134

**Comment by vjik** [comment]
Now I don't see duplication in output `release/what`. @xepozz , this problem is actual?

**Comment by xepozz** [comment]
Who knows ¯\\\_(ツ)\_/¯
