### ISSUE TITLE
README says 7.4 or higher needed, but composer.json requires ^8.0

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-dev-tool#214]
### What steps will reproduce the problem?

I noticed that the builds for the Docker image are failiing since a while, see https://github.com/yiisoft/yii-docker/actions/runs/2224229229

We're using the dev tool in the build to run some basic tests, but it requires PHP `^8.0`, despite stating 7.4 in the README.
See also https://github.com/yiisoft/yii-dev-tool/blob/master/composer.json#L16

### What is the expected result?

The repo should run with PHP 7.4

### What do you get instead?

Error that 8.0 is required.

**Comment by samdark** [comment]
8.0 is correct. I'll update readme.

**Comment by samdark** [comment]
Done.

**Comment by schmunk42** [comment]
OK, I'll stop building 7.4 images for `yii-docker` (Yii 3) then.
