### ISSUE TITLE
Package configuration structure

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii-dev-tool#27]
When I was working on PR #21 I realized that logic of declaring packages in the package configuration is strange...

Suppose the [main package configuration](https://github.com/yiisoft/yii-dev-tool/blob/b77e5d56973d52cb078f522872759f87638a908b/packages.php) looks like this:
```php
<?php
$packages = [
    'yiisoft/di' => 'di',
    'yiisoft/injector' => 'injector',
    'yiisoft/factory' => 'factory',
    'yiisoft/access' => 'access',
];
if (file_exists($localFile = __DIR__ . '/packages.local.php')) {
    $packages = array_merge($packages, require $localFile);
}
return $packages;
```

Suppose my own `packages.local.php` looks like this:
```php
<?php

$packages = [
    'rugabarbo/di' => 'di',
    'rugabarbo/docs' => 'docs',
    'rugabarbo/factory' => 'factory',
    'rugabarbo/yii-captcha' => 'yii-captcha',
];

return $packages;
```

The array keys are the names of GitHub repositories, and the values are the names of `/yii-dev-tool/dev/` subdirectories. It would be logical for my package `factory` to replace yii package `factory` after merge, but after merge we get the following array:

```php
[
    'yiisoft/di' => 'di',
    'yiisoft/injector' => 'injector',
    'yiisoft/factory' => 'factory',
    'yiisoft/access' => 'access',
    'rugabarbo/di' => 'di',
    'rugabarbo/docs' => 'docs',
    'rugabarbo/factory' => 'factory',
    'rugabarbo/yii-captcha' => 'yii-captcha',
];
```

Here we see that folders `di` and `factory` are each connected to two different repositories, but the logic of the tool is such that the code from only one repository will actually be installed in the folder. And the most interesting: **which one will be installed depends on the sequence of user actions** :)

So something is wrong here. Function `array_merge()` doesn't seem to be suitable for merging these configurations or the configuration structure itself should be different.

**Comment by samdark** [comment]
Yes. Should be replacing, not merging.

**Comment by rugabarbo** [comment]
I suggest the following configuration structure:

```php
[
    'yiisoft/di' => true, // install the package
    'yiisoft/injector' => 'rugabarbo/injector', // replace one package with another
    'yiisoft/factory' => 'yiisoft/factory-experimental', // another example of replace
    'yiisoft/access' => false, // do not install the package in the directory `dev` at all
]
```

In the configuration, **we only need names of repositories**. We do not need to specify any directories.

**Comment by samdark** [comment]
Looks OK to me.

**Comment by rugabarbo** [comment]
Аt the same time, I want to remove `--http` option. It seems to me that it is not needed and everything can be done more conveniently. I propose the following design:
```php
[
    'yiisoft/di' => true,
    // use https://github.com/yiisoft/di.git

    'yiisoft/injector' => 'rugabarbo/injector',
    // use git@github.com:rugabarbo/injector.git
    
    'yiisoft/factory' => 'https://github.com/yiisoft/factory-experimental.git',
    // explicit instruction to use https://github.com/yiisoft/factory-experimental.git
]
```

In sum: 
1. Packages that have not been replaced are installed using **https**.
2. Packages that have been replaced are installed using **git protocol**.
3. Packages for which the full repository address is specified are installed using this address.

@samdark what do you think about it?

**Comment by samdark** [comment]
> Packages that have not been replaced are installed using https.

I'd prefer git protocol for this case. That's what I'm using.

**Comment by rugabarbo** [comment]
Good case. Thanks :) 
This is what I suspected...

**Comment by rugabarbo** [comment]
Ok, now I see it as follows. 

**Configuration structure:**
```php
[
    'di' => true, // install the yiisoft package from GitHub using SSH
    // use git@github.com:yiisoft/di.git

    'yii-console' => 'https', // install the yiisoft package from GitHub using HTTPS
    // use https://github.com/yiisoft/yii-console.git

    'injector' => 'rugabarbo/injector', // install own fork from GitHub using SSH
    // use git@github.com:rugabarbo/injector.git

    'db' => 'https://samdark@bitbucket.org/yii/db.git',  // install using the specified repository address
    // use https://samdark@bitbucket.org/yii/db.git
    
    'access' => false, // do not install at all
]
```

**Console interface:**
```bash
# install 'di' package
./yii-dev install di

# show status of several packages
./yii-dev status di,injector,db
```
