### ISSUE TITLE
Using --http fails...

### ISSUE THREAD

**Issue by BillHeaton** [yiisoft/yii-dev-tool#28]
If you use `--httpd` the result is that the help text is displayed.  The problem is that adding the option moves where the command is located in $argv.

To get it working, I separated the command line processing into a  new class: src/command/Args.php and using getopt() to parse with both long and short arguments specified. 

Added `--verbose` for future use.  

Will wait on pull request until I get a go signal. You can preview at BillHeaton/yii-dev-tool.  Look for yii-dev-tool-fix-28.

**Comment by rugabarbo** [comment]
Just send a PR and we'll review it.
