### ISSUE TITLE
Automatically configure git upstream for repository forks

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii-dev-tool#31]
Command `./yii-dev install [<packages>]` can automatically set upstream for repository forks. It's can be achieved by internal execution of git command `git remote add upstream https://github.com/yiisoft/<repository>.git`.

For those developers who use forks, this would eliminate most of the routine when setting up the environment.

**Comment by samdark** [comment]
Great idea. Note though that core team members do not use forks.

**Comment by rugabarbo** [comment]
> core team members do not use forks.

Upstream will be installed only for those who replaced yiisoft package with their own non-yiisoft package in the configuration.

**Comment by rugabarbo** [comment]
Also, command `./yii-dev pull` should pull changes from the upstreams by default, and not from the forks. This is much more logical for forks.
