### ISSUE TITLE
Involve people in the development of Yii3, show yii-dev-tool usage examples

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii-dev-tool#39]
We do not have detailed explanations on how to use `yii-dev-tool`. **Especially not enough examples of use.** This can reduce the involvement of people in the development.

I propose to add:
- [x] Workflow examples in `yii-dev-tool` README
- [x] Cross references in `yiisoft/docs`
- [x] Forum post

---

Related docs:
* [yiisoft/yii-dev-tool – README](https://github.com/yiisoft/yii-dev-tool/blob/master/README.md)
* [yiisoft/docs – Yii Development Tool](https://github.com/yiisoft/docs/blob/master/005-development-tool.md)

Related forum posts:
* [Yii development tool](https://forum.yiiframework.com/t/yii-development-tool/126335)
* [Contributing to Yii 3](https://forum.yiiframework.com/t/contributing-to-yii-3/127369)

**Comment by samdark** [comment]
Agree.

**Comment by samdark** [comment]
@rugabarbo what's left on this one?

**Comment by rugabarbo** [comment]
> what's left on this one?

1) I'll change [yiisoft/docs page](https://github.com/yiisoft/docs/blob/master/005-development-tool.md) about the tool a bit.
2) I'll write a new forum post on yiiframework.com on how to use **yii-dev-tool** and add a link to usage example in README file.

**Comment by rugabarbo** [comment]
I have added a post to the forum: https://forum.yiiframework.com/t/a-detailed-example-of-how-to-contribute-to-yii-3-0/127909
