### ISSUE TITLE
`yii-dev update` for fork :fatal: No such remote 'origin   upstream'

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-dev-tool#42]
OS: Windows 10
`packages.local.php`:
```php
$packages = [
    'auth' => 'https',
    'yii-console' => 'https://github.com/roxblnfk/yii-console.git',
    'yii-cycle' => 'https://github.com/roxblnfk/yii-cycle.git',
    'yii-web' => 'https://github.com/roxblnfk/yii-web.git',
    'yii-demo' => 'https://github.com/roxblnfk/yii-demo.git',
];
```
Can't execute `yii-dev update` for any forked package

`yii-dev update auth` works good

`yii-dev update yii-console` works not good : 
![image](https://user-images.githubusercontent.com/4152481/69284365-8722eb00-0bff-11ea-80c6-2e694733fcc7.png)

`upstream` and `origin` configured automatically:
![image](https://user-images.githubusercontent.com/4152481/69284478-c5200f00-0bff-11ea-928c-178650908b4a.png)

**Comment by samdark** [comment]
@rugabarbo would you please take a look?

**Comment by rugabarbo** [comment]
@samdark yes, already trying to understand )

**Comment by rugabarbo** [comment]
@roxblnfk I can not reproduce the problem locally.

Please execute the following commands in the console:
```bash
cd yii-dev-tool
cd dev/yii-console && git --version && git remote -v
```

And give me a console output.

**Comment by roxblnfk** [comment]
```
D:\yii-dev-tool>cd dev/yii-console && git --version && git remote -v
git version 2.23.0.windows.1
origin  https://github.com/roxblnfk/yii-console.git (fetch)
origin  https://github.com/roxblnfk/yii-console.git (push)
upstream        https://github.com/yiisoft/yii-console.git (fetch)
upstream        https://github.com/yiisoft/yii-console.git (push)
```

**Comment by rugabarbo** [comment]
@roxblnfk thank you.

I found the problem in a third-party package [git-wrapper](https://github.com/cpliakas/git-wrapper) and I'm preparing a pull request for it. It will take some time.

For our package (`yii-dev-tool`), I am currently preparing a temporary solution that will help you. Wait a bit.

**Comment by rugabarbo** [comment]
@roxblnfk done. 

Update your local package `yii-dev-tool` with `git pull` and there will be no more errors.

**Comment by roxblnfk** [comment]
Good work! Thanks you
