### ISSUE TITLE
Ready-to-use Vagrant configuration 

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii-dev-tool#45]
All this time I have been using [my Vargant configuration](https://github.com/rugabarbo/yii-dev-vagrant) for **yii-dev-tool**. 

This is a ready-to-use Vagrant playground that can be used to develop `Yii3` packages. This is an alternative to Docker. It contains:
* Ubuntu 18.04
* PHP 7.2
* Composer with prestissimo plugin
* xDebug
* unzip, htop, mc (Midnight Commander)
* some other handy presets

In the future, we can add web configurations for packages like `yii-demo` to this Vagrant configuration.

I suggest adding it directly to **yii-dev-tool** repository so that it is available to run right from the **yii-dev-tool** package.

**Comment by samdark** [comment]
I don't mind. Let's have it.
