### ISSUE TITLE
Proxy git arguments

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-dev-tool#53]
Proxying git command arguments as is i.e. `./yii-dev git/commit --message="xxxx" --amend` etc. would make working with git batch commands more convenient.

Alternative idea is to have a command that just does a batch execution of any commands in each repository.

**Comment by rugabarbo** [comment]
My experience is that proxying options in scripting is a bad idea. There is a whole set of DX and UX problems that arises with this approach.

I created a universal console command `./yii-dev exec`. It will be useful not only in this case, but also in many others. And this is a clearer approach in terms of UX.
