### ISSUE TITLE
fix-dependencies doesn't detect unused interfaces

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-dev-tool#89]
1. Add `"psr/container": "^1.0",` to `composer.json` to any package.
2. Run `fix-dependencies`.

Expected to see `psr/container` removed. Actually getting "Nothing to fix" message.

**Comment by rugabarbo** [comment]
This was actually a serious bug. I fixed it and improved the plugins and binaries recognition. Hopefully, in the future I can add more tests and test more cases.
