### ISSUE TITLE
Ability to test any packages

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-dev-tool#99]
I think "test" command may be very handy.
For example, I've modified one related package and want to test another packages.

## Problem
Modified package can't be tested as an integration of some packages.

## User story
As a developer I want to call in console `./yii-dev test [packages delimited with comma]` and all selected packages should be tested.

## Possible solution
Implement `composer test` command in any `yiisoft/*` packages.
`./yii-dev test [packages delimited with comma]` will check if command is available then it will be called.

**Comment by samdark** [comment]
Sounds interesting. I see it as a good way not to cd to `dev/package` and not to run `./vendor/bin/whatever` all the time.

**Comment by xepozz** [comment]
I suggest to make two iterations:
1. Add command that will do `./vendor/bin/phpunit`
1. Modify command and replace `./vendor/bin/phpunit` with `composer test`

**Comment by samdark** [comment]
Or it can try `composer test` and, if it fails, run phpunit.

**Comment by xepozz** [comment]
Ok I'll try it.
